### ISSUE TITLE
From XML to CSV

### ISSUE THREAD

**Issue by alex-y-su** [cesarferreira/international#1]
Hello, is there any way how to get initial CSV? I have a lot of translation already in place and want to generate CSV from. Any hope you can implement it in this helpful util?

Not really an issue, but a suggestion.

**Comment by cesarferreira** [comment]
Hey mate,
sorry I didn't understand what you said, can you elaborate?

**Comment by alex-y-su** [comment]
Sorry for my English :) I just want to know is it possible to make CSV from Android resources (revers operation). For example if I already have translations for DE and SE languages and want to start use your util for adding more translations.

**Comment by cesarferreira** [comment]
I'm not planning on implementing that feature for now, thanks for the suggestion tho!
